# Generated by Django 5.2.3 on 2025-06-27 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_term_assignment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date for which attendance is recorded.')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', help_text='Attendance status (Present, Absent, Late, Excused).', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time when the attendance record was created/last updated.')),
                ('_class', models.ForeignKey(help_text='The class for which this attendance is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to='schoolApp.class')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='The teacher who recorded this attendance.', limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student whose attendance is being recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schoolApp.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '_class__name', 'student__last_name'],
                'unique_together': {('student', 'date', '_class')},
            },
        ),
    ]
