# Generated by Django 5.2.3 on 2025-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique slug for the class, auto-generated from the name.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique slug for the subject, auto-generated from the name.', max_length=100, null=True, unique=True),
        ),
    ]
