# Generated by Django 5.2.4 on 2025-07-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0007_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('text_file', 'Text/File Submission'), ('mcq', 'Multiple Choice Questions')], default='text_file', help_text='Type of assignment: text/file submission or multiple choice questions.', max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The text of the multiple choice question.')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, help_text='Points awarded for correctly answering this question.', max_digits=5)),
                ('assignment', models.ForeignKey(help_text='The MCQ assignment this question belongs to.', limit_choices_to={'assignment_type': 'mcq'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schoolApp.assignment')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='The text of the choice option.', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Designates if this choice is the correct answer.')),
                ('question', models.ForeignKey(help_text='The question this choice belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='schoolApp.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text="Indicates if the student's chosen answer was correct.")),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0.0, help_text='Points awarded for this question.', max_digits=5)),
                ('chosen_choice', models.ForeignKey(blank=True, help_text='The choice selected by the student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by_students', to='schoolApp.choice')),
                ('question', models.ForeignKey(help_text='The question this answer is for.', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='schoolApp.question')),
                ('submission', models.ForeignKey(help_text='The overall submission this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='schoolApp.submission')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
