# Generated by Django 5.2.4 on 2025-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0008_assignment_assignment_type_question_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the assignment.', null=True),
        ),
    ]
